<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56778" started-at="2018-10-24T21:09:03Z" finished-at="2018-10-24T21:10:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56778" started-at="2018-10-24T21:09:03Z" finished-at="2018-10-24T21:10:00Z">
      <class name="testcases.LaunchTheUrl">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.LaunchTheUrl@235b8e]" name="beforeSuite" is-config="true" duration-ms="924" started-at="2018-10-24T14:09:02Z" finished-at="2018-10-24T14:09:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testcases.LaunchTheUrl@235b8e]" name="setData" is-config="true" duration-ms="1" started-at="2018-10-24T14:09:03Z" finished-at="2018-10-24T14:09:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.LaunchTheUrl@235b8e]" name="beforeClass" is-config="true" duration-ms="2" started-at="2018-10-24T14:09:03Z" finished-at="2018-10-24T14:09:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.LaunchTheUrl@235b8e]" name="beforeMethod" is-config="true" duration-ms="14840" started-at="2018-10-24T14:09:03Z" finished-at="2018-10-24T14:09:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifysearch()[pri:0, instance:testcases.LaunchTheUrl@235b8e]" name="verifysearch" duration-ms="40662" started-at="2018-10-24T14:09:18Z" finished-at="2018-10-24T14:09:59Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeExceptionat utils.Reporter.reportStep(Reporter.java:61)at utils.Reporter.reportStep(Reporter.java:71)at wdMethods.SeMethods.verifyDisplayed(SeMethods.java:303)at pages.HomePage_RRS.verifysearchbutton(HomePage_RRS.java:24)at testcases.LaunchTheUrl.verifysearch(LaunchTheUrl.java:26)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:483)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifysearch -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.LaunchTheUrl@235b8e]" name="afterMethod" is-config="true" duration-ms="1185" started-at="2018-10-24T14:09:59Z" finished-at="2018-10-24T14:10:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testcases.LaunchTheUrl@235b8e]" name="afterTest" is-config="true" duration-ms="1" started-at="2018-10-24T14:10:00Z" finished-at="2018-10-24T14:10:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcases.LaunchTheUrl@235b8e]" name="afterSuite" is-config="true" duration-ms="806" started-at="2018-10-24T14:10:00Z" finished-at="2018-10-24T14:10:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.LaunchTheUrl -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
